security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: YWFkOTFlOWYyOGMxOWRhNzgxM2U0YjY2ZTg5MDIwNzBlNDhkYWFmOTI2M2YwNmI1Njk4ZGFiZjA0NTJlYWU2MWJjZGEwZTZjMTk2YzY4MmI3MjQ5ZDAxMDNlNDNjMWNhZTQ5ZDE0YjUzNzI2ZGUzNjdlNjNhMjE5OTdiMDgxMGU=
        # Token is valid 24 hours
        access-token-validity-in-seconds: 8640000
        access-token-validity-in-seconds-for-remember-me: 2592000
        refresh-token-validity-in-s:econds: 8640000

basepath:
    baseApi: /api/v1/
    baseUri: file:///C:/Users/ASUS/OneDrive/Desktop/javaLearning/New%20folder/upload/

file:
    spring:
      servlet:
        multipart:
          max-file-size: 52428800
          max-request-size: 52428800
    allowedExtension: pdf,jpg,jpeg,png,doc,docx
    allowedMimeTypes: application/pdf,image/jpeg,image/png,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document