security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: YWFkOTFlOWYyOGMxOWRhNzgxM2U0YjY2ZTg5MDIwNzBlNDhkYWFmOTI2M2YwNmI1Njk4ZGFiZjA0NTJlYWU2MWJjZGEwZTZjMTk2YzY4MmI3MjQ5ZDAxMDNlNDNjMWNhZTQ5ZDE0YjUzNzI2ZGUzNjdlNjNhMjE5OTdiMDgxMGU=
        # Token is valid 24 hours
        token-validity-in-seconds: 8640000
        token-validity-in-seconds-for-remember-me: 2592000